#!/sbin/runscript

opts="start stop restart"

start() {
	ebegin "Starting Perforce Server"

	touch $LOG_FILE
	chown perforce:perforce $LOG_FILE
	chmod 600 $LOG_FILE
	
	start-stop-daemon --start --quiet --exec /usr/sbin/p4d -c perforce -- -d -r $ROOT_DIRECTORY -J $JOURNAL_FILE -p $PORT -L $LOG_FILE -q

	sleep 2

	if ! pgrep p4d &> /dev/null
	then
		eerror "p4d could not be started! Check logfile $LOG_FILE"
		eend 1
		return 1
	fi
	eend $?
}

stop() {
	ebegin "Stopping Perforce Server"
	start-stop-daemon --stop --quiet --exec /usr/sbin/p4d 
	eend $?
}

restart() {
	svc_stop
	svc_start
}
